export * from "./post.model";
export * from "./homepagePosts.model";
export * from "./serviceCard.model";
export * from "./whatWeGotCards.model";
export * from "./thanksSchools.model";
export * from "./tatugaSchoolPost.model";
export * from "./taboo.model";
export * from "./commonQuestion.model";
export * from "./announcement.model";
